<?php
/**
 * @file
 * Add template file for the social buttons.
 */

/**
 * Implements hook_theme().
 *
 * Defines template files for the social sharing buttons module.
 */
function better_social_sharing_buttons_theme($existing, $type, $theme, $path) {
  return [
    'better_social_sharing_buttons' => [
      'variables' => ['items' => ''],
      'template' => 'better-social-sharing-buttons',
      'path' => $path . '/theme',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function  better_social_sharing_buttons_preprocess_better_social_sharing_buttons(&$variables) {
  $variables['social_buttons_sprite'] = '/' . drupal_get_path('module', 'better_social_sharing_buttons') . '/assets/dist/sprites/' . \Drupal::state('better_social_sharing_buttons.settings')->get('iconset') . '.svg';
}
