<?php

/**
 * @file
 * Add template file for the social buttons.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 *
 * Defines template files for the social sharing buttons module.
 */
function better_social_sharing_buttons_theme($existing, $type, $theme, $path) {
  return [
    'better_social_sharing_buttons' => [
      'variables' => ['items' => ''],
      'template' => 'better-social-sharing-buttons',
      'path' => $path . '/theme',
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function better_social_sharing_buttons_entity_extra_field_info() {
  if (\Drupal::config('better_social_sharing_buttons.settings')->get('node_field')) {
    $extra = [];
    foreach (NodeType::loadMultiple() as $bundle) {
      $extra['node'][$bundle->Id()]['display']['sharing_buttons'] = [
        'label' => t('Better Social Sharing Buttons'),
        'description' => '',
        'weight' => 100,
        'visible' => TRUE,
      ];
    }

    return $extra;
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function better_social_sharing_buttons_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('sharing_buttons')) {
    $config = \Drupal::config('better_social_sharing_buttons.settings');

    $items = [];
    global $base_url;

    $items['page_url'] = Url::fromRoute('<current>', [], ['absolute' => TRUE]);
    $items['description'] = '';
    $items['title'] = $entity->get('title')->value;
    $items['width'] = $config->get('width');
    $items['radius'] = $config->get('radius');
    $items['facebook_app_id'] = $config->get('facebook_app_id');
    $items['print_css'] = $config->get('print_css');
    $items['iconset'] = $config->get('iconset');
    $items['services'] = $config->get('services');
    $items['base_url'] = $base_url;

    $build['sharing_buttons'] = [
      '#theme' => 'better_social_sharing_buttons',
      '#items' => $items,
    ];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function better_social_sharing_buttons_preprocess_better_social_sharing_buttons(&$variables) {
  if (isset($variables['items']['iconset'])) {
    $variables['social_buttons_sprite'] = '/' . drupal_get_path('module', 'better_social_sharing_buttons') . '/assets/dist/sprites/' . $variables['items']['iconset'] . '.svg';
    $variables['items']['iconset'];
  }
  else {
    $config = \Drupal::config('better_social_sharing_buttons.settings');
    $variables['social_buttons_sprite'] = '/' . drupal_get_path('module', 'better_social_sharing_buttons') . '/assets/dist/sprites/' . $config->get('iconset') . '.svg';
  }
}

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function better_social_sharing_buttons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the better_social_sharing_buttons module.
    case 'help.page.better_social_sharing_buttons':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add social sharing buttons to your website.') . '</p>';
      return $output;

    default:
  }
}
